### ISSUE TITLE
Create Association Class for Card-Tag relation

### ISSUE THREAD

**Issue by jethrokuan** [CS2103JAN2018-W09-B4/main#53]
Right now we place tags within Card, but we often have to search for all cards with a particular tag. It would make more sense if the Card<->Tag relation be captured by an association class.

I am thinking of having a singleton, and implementing it using an adjacency list, or with guava's inbuilt graph library.

google.github.io/guava/releases/snapshot/api/docs/com/google/common/graph/Graph.html

This will be done in the following steps:

- [x] Remove `Tag` functionality from address Book  #55 
- [x] Morph `Person` into `Tag` 
  -  [x] Refactor Person to Tag #56 
  -  [x] Remove unused fields, and add relevant fields #57 
- [x] Create CardTag class #64 
- [x] create XMLAdaptedCardTag to store cardtag relations. #75

**Comment by jethrokuan** [comment]
This will be done in 3 steps:

1. Remove `Tag` functionality from address Book
2. Morph `Person` into `Tag`
3. Create CardTag class
4. create XMLAdaptedCardTag to store cardtag relations.

**Comment by jethrokuan** [comment]
Implementation is complete!

**Comment by jethrokuan** [comment]
Part of #83
